spring.datasource.url=jdbc:mysql://localhost:3306/spotlight
spring.datasource.username=AnshSawant
spring.datasource.password=AnshSawant

spring.jpa.hibernate.ddl-auto=update

fe.url=http://localhost:5173